### PR TITLE
Workflow that actually caches the dependencies.

### PR DESCRIPTION
**Pull request by realkaranvir**
Also shortened it to not have duplicate steps for pull requests versus pushes/merges to main. It uses a conditional check to determine whether to push to dockerhub.

### CODE REVIEW

**Review by bholt13 — COMMENTED** [review]
Check line 5, 73-75

**Review by JLpro-cd — APPROVED** [review]
Good Job, Karan

**Review by bholt13 — APPROVED** [review]
Looks good

**Review by JLpro-cd — APPROVED** [review]
Looks great now, finalized

**Review by thekevinWHYuan — APPROVED** [review]
LGTM!

**Review by StarDylan — APPROVED** [review]

**Pull request merged**
