### PR TITLE
[FEMR96] subtract amount from inventory

### PR DESCRIPTION
**Pull request by kevinzurek**
Subtracts from the current quantity of a medication on dispensing of the prescription (clicking submit on pharmacy)

https://teamfemr.atlassian.net/browse/FEMR-96

### CODE REVIEW

**Comment by kdunlap** [comment]
Everything seems to work pretty well here. In testing I found that replaced medications do not get marked as dispensed. Seems to be a fairly quick fix.

- create an encounter and all that jazz
- prescribe a medication in the medical tab
- replace that medication in pharmacy
- the remaining quantity does not get decremented

**Comment by kevinzurek** [comment]
@kdunlap good find. I ended up separating the action of "replacing", "dispensing", and "inventorying".

This actually uncovered another bug where it was thought that replacing was dispensing the medication as well, so replaced prescriptions were getting a date_dispensed of null.

Sorry for all the formatting changes in the diff :-1:

**Comment by kevinzurek** [comment]
I also rebased this branch so re-checking out will be necessary

**Comment by kdunlap** [comment]
Manually merged

**Pull request closed without merging**
