### PR TITLE
FEMR-97 Only show available available medications in typeahead

### PR DESCRIPTION
**Pull request by kdunlap**

### CODE REVIEW

**Comment by kdunlap** [comment]
https://teamfemr.atlassian.net/browse/FEMR-97

**Comment by kdunlap** [comment]
Noting for later: If no tripId (users not assigned to a trip), don't filter by tripId

**Comment by kevinzurek** [comment]
Something worth noting:

If there's no trip ID (even if there is a trip ID) and a user enters a medication outside of what is in the inventory, it will get logged as an old medication (pre-2.2.0) because it won't have a form. I think this means that it won't show up in typeahead which might actually be okay.

**Comment by kdunlap** [comment]
I agree that medications entered outside of inventory should not show up in the typeahead. 

I guess it could be possible that prescription ends up being used for something that can't be inventoried (not really sure how -- I'm not a doctor though). These types of questions are probably things we can tweak after getting some feedback.

**Comment by kdunlap** [comment]
Fixed minor issues with evolutions 95 and 87

**Pull request closed without merging**
