### PR TITLE
Adding functionality to allow user table to be sorted by email address

### PR DESCRIPTION
**Pull request by judyvbaxter**
[FEMR-243] Add functionality to User table, sort by email address.

### CODE REVIEW

**Comment by kevinzurek** [comment]
Ah yes, JavaScript :) Everything works very well except "Last Login" is being sorted by the first letter of the month instead of the actual date for me. I would recommend fixing or removing the sorting for this column. Thanks!!!

**Comment by judyvbaxter** [comment]
Ah yes, I did not seem to notice that when I was adding the sorting to the
other columns. I shall go in and remove this. Would you like me to submit
this as another pull request?

**Comment by kevinzurek** [comment]
Hi Judy - go ahead and push up another commit and we will merge 👍

**Comment by kevinzurek** [comment]
merged manually

https://teamfemr.atlassian.net/browse/FEMR-243

**Comment by kevinzurek** [comment]
Also completes

https://teamfemr.atlassian.net/browse/FEMR-50

**Pull request closed without merging**
