### PR TITLE
 Implementing PDF-Feature, Encounter must be closed

### PR DESCRIPTION
**Pull request by aserhan**

### CODE REVIEW

**Comment by aserhan** [comment]
I need andres pdf

**Comment by kevinzurek** [comment]
was this an accident?

**Comment by aserhan** [comment]
I was trying to pull Andres to a separate branch when we had to present song know if I was doing it right.

**Comment by kevinzurek** [comment]
see email!

**Comment by aserhan** [comment]
Perfect! 

Thank You! 

----- Original Message -----

**Pull request closed without merging**
